### ISSUE TITLE
Initial landing page

### ISSUE THREAD

**Issue by mjjstockman** [Boycey7/Social-stream-group-project#10]
# Home Page

## Tasks

- [x] Remove unwanted boiler template parts
- [x] Add basic structure of home page
- [x] Make sure semantic elements are used eg, main, header, footer, sections
