### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by Boycey7** [Boycey7/Social-stream-group-project#17]
# Style site

## Tasks

- [ ] Add global css
- [x] Make sure all spacings are constant, eg, space below h1's p's etc
- [x] Make sure enough white space
- [x] Consistant colour scheme
- [ ] Add font/s
