### ISSUE TITLE
Create basic structure of card

### ISSUE THREAD

**Issue by Boycey7** [Boycey7/Social-stream-group-project#3]
## Tasks
- [x] Include hardcoded user name
- [x] Include hardcoded dummy text
- [x] Add like icon with dummy count number
- [x] Add delete button
