### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by mjjstockman** [Boycey7/Social-stream-group-project#5]
# Create basic structure of card

## Tasks

- [ ] Include hardcoded user name
- [ ] Include hardcoded dummy text
- [ ] Add like icon with dummy count number
- [ ] Add delete button

**Comment by mjjstockman** [comment]
Dulpicate
